services:
  # ATTACKER'S PROXY - DNS poisoning endpoint
  proxy:
    image: nginx:alpine
    container_name: attacker_proxy
    ports: 
      - "80:80"      # HTTP - DNS poisoning landing
      - "8443:8443"  # HTTPS - Attacker's fake secure site  
      - "9443:9443"  # HTTPS - Proxy to real legitimate site
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      upstream:
        condition: service_healthy
    networks: 
      - attack_net

  # LEGITIMATE UPSTREAM SERVER
  upstream:
    image: nginx:alpine
    container_name: legitimate_server
    environment:
      HSTS: "on"
      HSTS_HEADER: "max-age=31536000; includeSubDomains; preload"
    volumes:
      - ./upstream/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./upstream/index.html:/usr/share/nginx/html/index.html:ro
      - ./certs:/etc/nginx/certs:ro
      - ./upstream/init.sh:/docker-entrypoint.d/10-init-hsts.sh:ro
    healthcheck:
      test: ["CMD", "sh", "-c", "apk add --no-cache curl >/dev/null 2>&1 || true; curl -kfs https://localhost/secure"]
      interval: 5s
      timeout: 3s
      retries: 12
    networks:
      attack_net:
        aliases:
          - upstream
    restart: unless-stopped

networks:
  attack_net: