services:
  proxy:
    image: nginx:alpine
    container_name: hs_proxy
    ports: ["80:80"]
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      upstream:
        condition: service_healthy
    networks: 
      lab:

  upstream:
    image: nginx:alpine
    container_name: hs_upstream
    environment: 
      - HSTS=off
    volumes:
      - ./upstream/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./upstream/index.html:/usr/share/nginx/html/index.html:ro
      - ./certs:/etc/nginx/certs:ro
    healthcheck:
      test: ["CMD", "sh", "-c", "apk add --no-cache curl >/dev/null 2>&1 || true; curl -kfs https://localhost/secure"]
      interval: 5s
      timeout: 3s
      retries: 12
    networks:
      lab:
        aliases:
          - upstream
    restart: unless-stopped

networks:
  lab: {}
