services:
  proxy:
    image: nginx:alpine
    container_name: hs_proxy
    ports:
      - "80:80"          # only expose 80 publicly
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [upstream]

  upstream:
    image: nginx:alpine
    container_name: hs_upstream
    environment:
      - HSTS=off         # set to on to demo protection
    volumes:
      - ./upstream/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./upstream/index.html:/usr/share/nginx/html/index.html:ro
      - ./certs:/etc/nginx/certs:ro
